# true — плагин сам слушает урон и отображает индикатор
# false — только API, другие плагины самостоятельно вызывают спавн индикатора
self-working: true

# Шаблоны для индикатора, поддерживают форматирование MiniMessage - https://docs.papermc.io/adventure/minimessage/
templates:
  # Стандартный шаблон для урона, отображается всегда, если не отображается другой
  default: "<red>-<damage> ❤</red>"

  # Шаблон индикатора критического удара, заменяет шаблон индикатора если удар критический.
  crit: "<gold>-<damage> ❤</gold>"

# Анимация появления и исчезновения индикатора
animation:
  # Длительность фазы подлёта индикатора в тиках
  rise-ticks: 22

  # Длительность фазы исчезновения индикатора
  fade-ticks: 7

  # Высота подъёма индикатора от точки спавна за время 'rise-ticks'
  rise-height: 0.7

# Настройка отображения индикатора
display:
  # Скейл индикатора, позволяет увеличить или уменьшить индикатор
  scale: 1.0

  # Включение/Отключение тени индикатора
  shadowed: false

  # Изменение цвета бэкграунда индикатора. Формат ARGB
  background-color:
    a: 160
    r: 20
    g: 20
    b: 20